language: node_js
before_script: npm test
script: npm run build
deploy:
  provider: pages
  local-dir: ./dist
  fqdn: knowledge.extrategy.net
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
env:
  - GOGGLE_CLIENT_ID=1
  - GOGGLE_API_KEY=1
  - PIPEDRIVE_API_TOKEN=1
  - PIPEDRIVE_COMPANY_DOMAIN=ideato
  - BASE_GOOGLE_DRIVE_DIRECTORY=1WZS3_nShJv-Im3xPd69UytYHl0mWstkD
