language: node_js
before_script: npm test
script: npm run build
deploy:
  provider: pages
  local-dir: ./dist
  fqdn: knowledge.extrategy.net
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
